name: firstapp
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  bloc: ^8.0.1
  http: ^0.13.4
  equatable: ^2.0.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - echo "Installing Flutter SDK"
            - git clone https://github.com/flutter/flutter.git -b stable --single-branch
            - export PATH="$PATH:pwd/flutter/bin"
            - flutter doctor
            - flutter pub get
        build:
          commands:
            - flutter build web
        postBuild:
          commands:
            - echo "Build completed"
      artifacts:
        baseDirectory: build/web
        files:
          - '*/'
      cache:
        paths:
          - 'flutter/.pub-cache/*'
          - 'build/*'